#!/bin/bash
#
# 主要分析 wuftpd 這個服務所產生的 logfile 資料，
# 分析的是 /var/log/messages 這個檔案
#
# Writtern by VBird
#
# 2004/12/28    VBird   Released
# 2005/01/05    VBird   因為 awk 不再需要 \ 跳脫 % ，所以修訂之！
#
#####################################################################
# 4 Wu-FTP 的登錄資料的功能函數 (Function) ！
funcwuftp () {
	echo "================= FTP 的登錄檔資訊彙整 ======================="	>> $logfile
	wuftpright=`cat $basedir/messageslog|grep "FTP LOGIN" | wc -l | \
		awk '{print $1}'`
	if [ "$wuftpright" != "0" ]; then
		echo "Wu-FTP-成功登入次數: $wuftpright" | \
			awk '{printf( "%-41s %3d\n", $1, $2)}'		>> $logfile
		echo "帳號   來源位址 次數 "| \
			awk '{printf("%-15s %-25s %-4s\n", $1, $2, $3)}'	>> $logfile
		cat $basedir/messageslog | grep "FTP LOGIN" | \
			sed 's/^.*,//g' | awk '{print $1}' \
			> $basedir/messageswuftp-1
		cat $basedir/messageslog | grep "FTP LOGIN" | \
			sed 's/^.*FROM//g' | awk '{print $1}' \
			> $basedir/messageswuftp-2
		paste $basedir/messageswuftp-1 $basedir/messageswuftp-2 \
			> $basedir/messageswuftp
		/bin/awk '{ for( i=0; i<1; i++ ) Number[$i]++ };
			END{ for( course in Number )
			printf( "%-35s %3d\n", course, Number[course])}' \
			$basedir/messageswuftp  | sort -k 3 -gr | \
			awk '{printf("%-15s %-25s %3d\n", $1, $2, $3)}'	>> $logfile
		echo " " 							>> $logfile
	fi
	wuftperror=`cat  $basedir/messageslog|grep "ftp.*auth.*fail" |\
		wc -l| awk '{print $1}'`
	if [ "$wuftperror" != "0" ]; then
		echo "Wu-FTP-錯誤登入次數: $wuftperror" | \
			awk '{printf( "%-41s %3d\n", $1, $2)}'		>> $logfile
		cat $basedir/messageslog |grep "ftp.*auth.*fail" | \
			sed 's/^.*\buser=//g' | awk '{print $1}' \
			> $basedir/messageswuftpno.1.tmp
		awk -v mon=`date +%b` '{ if( $1 != mon ) print $1; 
			if( $1 == mon ) print "UnknowUser" }' \
			$basedir/messageswuftpno.1.tmp  \
			> $basedir/messageswuftpno.1
		cat $basedir/messageslog |grep "ftp.*auth.*fail" | \
			sed 's/^.*rhost=//g' | awk '{print $1}' \
			> $basedir/messageswuftpno.2
		paste $basedir/messageswuftpno.1 $basedir/messageswuftpno.2 \
			> $basedir/messageswuftpno
		/bin/awk '{ for( i=0; i<1; i++ ) Number[$i]++ };
			END{ for( course in Number )
			printf( "%-35s %3d\n", course, Number[course])}' \
			$basedir/messageswuftpno| sort -k 3 -gr | \
			awk '{printf("%-15s %-25s %3d\n", $1, $2, $3)}' 	>> $logfile
		echo " "							>> $logfile
	fi
	if [ "$wuftpright" == "0" ] && [ "$wuftperror" == "0" ]; then
		echo "今日沒有使用 Wu FTP 的紀錄"				>> $logfile
		echo " "							>> $logfile
	fi
}

