#!/bin/bash

# A program can change the speicic route according the different usage.
# Usage 'route_change [-a/d]'
# Created: July 31 2012,Charles Shi

USAGE="Usage: $(basename $0) [-a/d]  "

MINPARAMS=1

# Check whether user input the gw that need to be changed to
if [ $# -lt "$MINPARAMS" ]
then
  echo
  echo "This script needs at least $MINPARAMS command-line arguments!"
  echo $USAGE
  exit 1
fi  


# Display the initial route information
echo ' '
echo '********* Route Information ********* '
ip route | grep via
echo '************************************* '

if [ "$1" == "-a" ]; then
	"$(sudo route add -net  91.189.0.0/16 gw 10.20.70.254)"
fi

if [ "$1" == "-d" ]; then
	"$(sudo sudo route del -net 91.189.0.0 netmask 255.255.0.0)"
fi

echo ' '
echo '********* New Route Information ********* '
ip route | grep via
echo '************************************* '


#
## Now remove the inital GW
#sudo route del default gw $GW
#sleep 2
## Change to new GW
#sudo route add default gw 10.20.70.$1
#
#echo ''
#echo '--------------------------------------'
## Display the result
#echo 'Success! Now the gateway is '`ip route | awk '/default/{print $3}'`
#echo ' '
#sleep 2
#
## Staring VPN connection
#echo '********* Starting VPN... ********* '
## Stop and start
#sudo vpnc-disconnect
#sleep 1
#sudo vpnc su
#
#
#if [ "$2" != "-ssh" ] ; then
#	 exit 1
#fi
#
## Staring SSH port mapping 
#echo '********* Starting SSH... ********* '
#
#existing_ssh="$(netstat -lntp | grep $LOCAL_PROXY_PORT | awk '{print $7}')"
#
#if [ $existing_ssh != "" -a $existing_ssh != "-" ] ; then 
#	echo "There is another process using this port: $existing_ssh , please kill it then start ssh again! "
#	exit 1
#else
#	sudo sshpass -p $SSH_SERVER_PASS ssh -D10.20.70.120:$LOCAL_PROXY_PORT $SSH_SERVER_USER@$SSH_SERVER
#fi
#
#exit 0
